### ISSUE TITLE
Implement Form Input Wave

### ISSUE THREAD

**Issue by FarshadJanmohammadi** [Code-Coterie-Team/Form-Input-Wave#1]
https://50projects50days.com/projects/form-wave/

**Comment by faeze-amn** [comment]
@FarshadJanmohammadi

**Comment by FarshadJanmohammadi** [comment]
سلام، چون لیبل ها که کل متن میشه موقع اکتیو استایل خاصی نمیگیره پس نیاز نیست کلاس اکتیو رو بهش بدی
